name: Python application test with Github Actions

# runs on push
on: [push]

jobs:
  build:
    # run job on latest version of ubuntu
    runs-on: ubuntu-latest
    
    # steps to run
    steps:
    # check out your repo so that the job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Insall dependencies
      run: |
        make install

    - name: Lint with Pylint
      run: |
        make lint
        
    - name: Test with Pytest
      run: |
        make test
        
    - name: Format code with Python black
      run: |
        make format
    
    
    
